services:
  test-task:
    image: local/test-task:latest
    build:
      context: .
    environment:
      - RUST_LOG=debug
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./dev/test-task/configs:/service/configs:ro
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - db-data:/data/db
    command: mongod --quiet --logpath /dev/null
  redis:
    image: redis
    ports:
      - 6379:6379
  nginx:
    image: nginx:alpine
    ports:
      - 8080:80
    depends_on:
      - test-task
    volumes:
      - ./dev/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
volumes:
  db-data:
